language: erlang

env:
   = GemStone-3.1.0.2
   - ST=PharoCore-1.1
   - ST=PharoCore-1.2
   - ST=PharoCore-1.3
   - ST=Pharo-1.4
   - ST=Squeak-4.3
   - ST=Squeak-4.4

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:
   - ./build.sh -i $ST -m -f "$PROJECT_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - ls -altr *
   - $BUILDER_CI_HOME/buildImageErrorCheck.sh
   - $BUILDER_CI_HOME/buildTravisStatusCheck.sh
#   - cat TravisTranscript.txt
