language: smalltalk
sudo: false

os: linux

smalltalk:
  - Pharo-6.1
    smalltalk_config:
      - .smalltalk-pharo6.ston
  - Pharo-6.0
#  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0
#  - GemStone-3.3.6
#  - GemStone-2.4.8
#  - GemStone-3.1.0.6
#  - GemStone-3.2.17
#  - Squeak-5.1
#  - Squeak-5.0
#  - Squeak-4.6
#  - Squeak-4.5
#  - Squeak-trunk

smalltalk_config:
  - .smalltalkA.ston
  - .smalltalkB.ston

#matrix:
#  allow_failures:
#    - smalltalk: Squeak-4.4
#    - smalltalk: Squeak-4.5
#    - smalltalk: Squeak-4.6
#    - smalltalk: Squeak-5.0
#    - smalltalk: Squeak-5.1
#    - smalltalk: Squeak-trunk

cache:
  directories:
    - $SMALLTALK_CI_CACHE
