language: erlang

# build matrix: "PharoCore-1.3" or "Squeak4.3" ... parallel tests for
#   all listed environments
env:
   - ST=PharoCore-1.3
   - ST=Squeak4.3

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - if [[ "$ST" == "Squeak4.3" ]]; then ./build_clone.sh -g "-b squeak4.3 git://github.com/dalehenrich/filetree.git"; fi
   - if [[ "$ST" == "PharoCore-1.3" ]]; then ./build_clone.sh -g "-b pharo1.3 git://github.com/dalehenrich/filetree.git"; fi
#   - ./build_clone.sh -g "git://github.com/dalehenrich/metacello-work.git"
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:

   - ./build.sh -i $ST -s latAmMirror.st -m -f "$PROJECT_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - if ( test -e PharoDebug.log ); then cat PharoDebug.log; fi
   - if ( test -e PharoDebug.log ); then die; fi
   - if ( test -e SqueakDebug.log ); then cat SqueakDebug.log; fi
   - if ( test -e SqueakDebug.log ); then die; fi
   - if ( test -e TravisCISuccess.txt ); then cat TravisCISuccess.txt; fi
   - if ( test -e TravisCIFailure.txt ); then cat TravisCIFailure.txt; fi
   - if ( test -e TravisCIFailure.txt ); then die; fi
